### ISSUE TITLE
Support of webpack 5

### ISSUE THREAD

**Issue by iegik** [mattlewis92/webpack-filter-warnings-plugin#35]
Has incorrect peerDependencies:

webpack-filter-warnings-plugin@1.2.1 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed.

**Comment by patrickmetz** [comment]
@iegik Webpack 5 doesn't need this plugin anymore. You can use ignoreWarnings: https://webpack.js.org/configuration/other-options/#ignorewarnings
